import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * 侧边栏由 docs/ 目录结构自动生成。
 *
 * 顺序与标题通过两处控制：
 *  1. 目录级：docs/<目录>/_category_.json 中的 label / position
 *  2. 文件级：md 文章头部的 `sidebar_position` 与 `sidebar_label`
 *
 * 新增一篇实验文档时无需改动本文件，放进 docs/ 即可。
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
